## 1. Let $I$ be the unit $n \times n$ matrix. Let $A$ be an $n \times r$ matrix. What is $I A$? If $A$ is an $m \times n$ matrix, what is $A I$?

### Solution

Let $A$ be an $n \times r$ matrix, then $I A$ is an $n \times r$ matrix, and its $i j$-component is

$$
0 a_{1 j} + ... + 0 a_{(i - 1) j} + 1 a_{i j} + 0 a_{(i + 1) j} + ... + 0 a_{n j} = a_{i j}
$$

Hence $I A = A$.

Let $A$ be an $m times n$ matrix, then $A I$ is an $m \times n$ matrix, and its $i j$-component is

$$
a_{i 1} 0 + ... + a_{i (j - 1)} 0 + a_{i j} 1 + a_{i (j + 1)} 0 + ... + a_{i n} 0 = a_{i j}
$$

Hence $A I = A$.

## 2. Let $\mathit{0}$ be the matrix all of whose coordinates are $0$. Let $A$ be a matrix of a size such that the product $A \mathit{0}$ is defined. What is $A \mathit{0}$?

### Solution

Let $A$ be an $m \times n$ matrix, and the size of $\mathit{0}$ be $n \times r$.

Then $A \mathit{0}$ is an $m \times r$ matrix where all of its component is $0$.

We can write

$$
A \mathit{0}_{n \times r} = \mathit{0}_{m \times r}
$$

## 4. 

Let $A, B$ be square matrices of the same size, and assume that $AB = BA$.

Show that 
$$
(A + B)^2 = A^2 +2 AB +B^2
$$

and

$$
(A + B) (A - B) = A^2 - B^2
$$

using the properties of matrices stated in [Theorem 3.1.](../2_3_multiplication_of_matrices.ipynb#Theorem-3.1.)

### Proof

Let $A, B$ be $n \times n$ matrices, and $A = (a_{i j})$ and

$$
\begin{equation}
\begin{aligned}
(A + B)^2 &= (A + B) (A + B) \\
&= (A + B) A + (A + B) B
\end{aligned}
\end{equation}
$$

$(A + B) A$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is

$$
(a_{i 1} + b_{i 1}) a_{1 j} + (a_{i 2} + b_{i 2}) a_{2 j} + ... + (a_{i n} + b_{i n}) a_{n j} = \sum_{k = 1}^{n} (a_{i k} + b_{i k}) a_{k j}
$$

And $(A + B) B$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is

$$
(a_{i 1} + b_{i 1}) b_{1 j} + (a_{i 2} + b_{i 2}) b_{2 j} + ... + (a_{i n} + b_{i n}) b_{n j} = \sum_{k = 1}^{n} (a_{i k} + b_{i k}) b_{k j}
$$

Then $((A + B)^2 = (A + B) A + (A + B) B$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is

$$
\begin{equation}
\begin{aligned}
\sum_{k = 1}^{n} (a_{i k} + b_{i k}) a_{k j} + \sum_{k = 1}^{n} (a_{i k} + b_{i k}) b_{k j} &= \sum_{k = 1}^{n} (a_{i k} + b_{i k}) (a_{k j} + b_{k j}) \\
&= \sum_{k = 1}^{n} (a_{i k} a_{k j} + a_{i k} b_{k j} + b_{i k} a_{k j} + b_{i k} b_{k j}) \\
&= \sum_{k = 1}^{n} (a_{i k} a_{k j}) + \sum_{k = 1}^{n} a_{i k} b_{k j} + \sum_{k = 1}^{n} b_{i k} a_{k j} + \sum_{k = 1}^{n} b_{i k} b_{k j}
\end{aligned}
\end{equation}
$$

Meanwhile, we know that

- $A^2$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is $\sum_{k = 1}^{n} a_{i k} a_{k j}$
- $B^2$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is $\sum_{k = 1}^{n} b_{i k} b_{k j}$
- $A B$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is $\sum_{k = 1}^{n} a_{i k} b_{k j}$
- $B A$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is $\sum_{k = 1}^{n} b_{i k} a_{k j}$

Since it is assumed that $A B = B A$, then
$$
(A + B)^2 = A^2 + A B + B A + B^2 = A^2 + 2 A B + B^2
$$

And

$$
\begin{equation}
\begin{aligned}
(A + B) (A - B) &= (A + B) (A + (-1 B)) \\
&= (A + B) A + (A + B) (-1 B) \\
&= (A + B) A + (-1) (A + B) B \\
&= (A + B) A - (A + B) B \\
\end{aligned}
\end{equation}
$$

Then $(A + B) (A - B) = (A + B) A - (A + B) B$ is a square matrix with the same size of $A$ and $B$, and its $i j$-component is

$$
\begin{equation}
\begin{aligned}
\sum_{k = 1}^{n} (a_{i k} + b_{i k}) a_{k j} - \sum_{k = 1}^{n} (a_{i k} + b_{i k}) b_{k j} &= \sum_{k = 1}^{n} (a_{i k} + b_{i k}) (a_{k j} - b_{k j}) \\
&= \sum_{k = 1}^{n} (a_{i k} a_{k j} - a_{i k} b_{k j} + b_{i k} a_{k j} - b_{i k} b_{k j}) \\
&= \sum_{k = 1}^{n} (a_{i k} a_{k j}) - \sum_{k = 1}^{n} a_{i k} b_{k j} + \sum_{k = 1}^{n} b_{i k} a_{k j} - \sum_{k = 1}^{n} b_{i k} b_{k j}
\end{aligned}
\end{equation}
$$

Since it is assumed that $A B = B A$, then
$$
(A + B) (A - B) = A^2 - A B + B A - B^2 = A^2 - B^2
$$

Q.E.D.

## 5.

Let

$$
A = \begin{pmatrix}
1 & 2 \\
3 & -1
\end{pmatrix},
B = \begin{pmatrix}
2 & 0 \\
1 & 1
\end{pmatrix}
$$

Find $A B$ and $B A$.

### Solution

$$
\begin{equation}
\begin{aligned}
A B &= \begin{pmatrix}
1 & 2 \\
3 & -1
\end{pmatrix}
\begin{pmatrix}
2 & 0 \\
1 & 1
\end{pmatrix} \\
&= \begin{pmatrix}
4 & 2 \\
5 & -1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
B A &= \begin{pmatrix}
2 & 0 \\
1 & 1
\end{pmatrix}
\begin{pmatrix}
1 & 2 \\
3 & -1
\end{pmatrix}\\
&= \begin{pmatrix} 
2 & 4 \\
4 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

In [1]:
## Verify with numpy

import numpy as np

A = np.matrix([[1, 2], [3, -1]])
B = np.matrix([[2, 0], [1, 1]])

A.dot(B)

matrix([[ 4,  2],
        [ 5, -1]])

In [2]:
B.dot(A)

matrix([[2, 4],
        [4, 1]])

## 6.

Let

$$
C = \begin{pmatrix}
7 & 0 \\
0 & 7
\end{pmatrix}
$$

Let $A, B$ be as in Exercise 5. Find $CA, AC, CB$, and $BC$. State the general rule including this exercise as a special case.

### Solutions

$$
\begin{equation}
\begin{aligned}
C A &= \begin{pmatrix}
7 & 0 \\
0 & 7
\end{pmatrix}
\begin{pmatrix}
1 & 2 \\
3 & -1
\end{pmatrix} \\
&= \begin{pmatrix}
7 & 14 \\
21 & -7
\end{pmatrix} \\
&= 7 A
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
A C &= \begin{pmatrix}
1 & 2 \\
3 & -1
\end{pmatrix}
\begin{pmatrix}
7 & 0 \\
0 & 7
\end{pmatrix} \\
&= \begin{pmatrix}
7 & 14 \\
21 & - 7
\end{pmatrix} \\
&= 7 A
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
C B &= \begin{pmatrix}
7 & 0 \\
0 & 7
\end{pmatrix}
\begin{pmatrix}
2 & 0 \\
1 & 1
\end{pmatrix} \\
&= \begin{pmatrix}
14 & 0 \\
7 & 7
\end{pmatrix} \\
&= 7 B
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
B C &= \begin{pmatrix}
2 & 0 \\
1 & 1
\end{pmatrix}
\begin{pmatrix}
7 & 0 \\
0 & 7
\end{pmatrix} \\
&= \begin{pmatrix}
14 & 0 \\
7 & 7
\end{pmatrix} \\
&= 7 B
\end{aligned}
\end{equation}
$$

We also see that $C = 7 I_2$.

In [3]:
## Verify with numpy

C = 7 * np.eye(2)

C

array([[7., 0.],
       [0., 7.]])

In [4]:
print(f'C * A = {C * A}')
print(f'A * C = {A * C}')
print(f'C * B = {C * B}')
print(f'B * C = {B * C}')

C * A = [[ 7. 14.]
 [21. -7.]]
A * C = [[ 7. 14.]
 [21. -7.]]
C * B = [[14.  0.]
 [ 7.  7.]]
B * C = [[14.  0.]
 [ 7.  7.]]


#### Generalization

Let $A$ be $n \times n$ square matrices of field $K$. Let $c \in K$, and $C = c I_n$.

Show that $C A = c A$ and $A C = c A$.

**Proof**

First, we show $C_n A = c A$:

$$
C A = (c I_n) A = c (I_n A) = c A
$$

Then, we show $A C_n = c A$:

$$
A C = A (c I_n)
$$

From [Theorem 3.1.](../2_3_multiplication_of_matrices.ipynb#Theorem-3.1.), we have

$$
A (c I_n) = c (A I_n) = c A
$$

Hence $A C = c A$.

Q.E.D.

## 7.

Let $X = (1, 0, 0)$ and let

$$
A = \begin{pmatrix}
3 & 1 & 5 \\
2 & 0 & 1 \\
1 & 1 & 7
\end{pmatrix}
$$

What is $X A$?

### Solution

$$
\begin{equation}
\begin{aligned}
X A &= (1, 0, 0)
\begin{pmatrix}
3 & 1 & 5 \\
2 & 0 & 1 \\
1 & 1 & 7
\end{pmatrix} \\
&= (3, 1, 5)
\end{aligned}
\end{equation}
$$

In [5]:
## Verify with numpy

X = [1, 0, 0]
A = np.matrix([[3, 1, 5], [2, 0, 1], [1, 1, 7]])

X * A

matrix([[3, 1, 5]])

## 8. Let $X = (0,1,0)$, and let $A$ be an arbitrary $3 \times 3$ matrix. How would you describe $X A$? What if $X = (0, 0, 1)$? Generalize to similar statements concerning $n \times n$ matrices, and their products with unit vectors.

### Generalization

Let $A = (a_{i j})$ be a square $n \times n$ matrix. Let $X$ be the $n$-length unit vector with $i$-th coordinate be $1$.

Show that $X A = (a_{i 1}, ..., a_{i n})$, which is the $i$-th row of $A$.

**Proof**

We can see $X$ as a $1 \times n$ matrix.

Then $X A$ is a $1 \times n$ matrix, aka a $n$-length vector, and its $j$-th component is

$$
0 a_{1 j} + ... + 0 a_{(i - 1) j} + 1 a_{i j} + 0 a_{(i + 1) j} + ... + 0 a_{n j} = a_{i j}
$$

Hence $X A = (a_{i 1}, ... a_{i n})$. Q.E.D.

## 9. Prove (Skip)... If A, B, C are matrices which can be multiplied, show that $^t(A B C) = ^tC ^tB ^tA$.

### Proof

From [theorem 3.3](../2_3_multiplication_of_matrices.ipynb#Theorem-3.3.) we have

$$
^t(A B C) = ^t (A (B C)) = ^t (B C) ^tA = (^tC ^tB) ^tA
$$

And From [theorem 3.2](../2_3_multiplication_of_matrices.ipynb#Theorem-3.2.) we have

$$
(^tC ^tB) ^tA = ^tC (^tB ^tA) = ^tC ^tB ^tA
$$

Hence $^t(A B C) = ^tC ^tB ^tA$. Q.E.D.

## 10. Let $M$ be an $n \times n$ matrix such that $^tM = M$. Given two row vectors in $n$- space, say $A$ and $B$ define $\langle A, B \rangle$ to be $AM ^tB$. (Identify a $1 \times 1$ matrix with a number.) Show that the conditions of a scalar product are satisfied, except possibly the condition concerning positivity. Give an example of a matrix $M$ and vectors $A, B$ such that $AM ^tB$ is negative (taking $n = 2$).

Note: It is understood that by "the conditions of a scalar product" Lang refers to [SP 1, 2, 3 in chapter 1](../../1_vector_spaces/1_vector_spaces.ipynb#Properties-of-dot-products).

Hence we need to show
- **SP 1**. $\langle A, B \rangle = \langle B, A \rangle$
- **SP 2**. Let $C$ be row vectors in $n$-space. $\langle A, B + C \rangle = \langle A, B \rangle + \langle A, C \rangle$.
- **SP 3**. Let $K$ be the field under $A$ and $B$. Let $x \in K$, then
$$
\langle x A, B \rangle = x \langle A, B \rangle = \langle A, x B \rangle
$$

### Proof

#### SP 1

$$
\begin{equation}
\begin{aligned}
\langle A, B \rangle &= AM ^tB \\
&= ^t(^tA) ^t(^tM) ^tB \\
&= ^t(B ^tM ^tA) & \text{Conclusion of Exercise 9.} \\
&= B ^tM ^tA & \text{Since $AM ^tB$ is a $1 \times 1$ matrix.} \\
&= B M ^tA &\text{Since $^tM = M$}. \\
&= \langle B, A \rangle
\end{aligned}
\end{equation}
$$

#### SP 2

$$
\langle A, B + C \rangle = AM ^t(B + C)
$$

From the [conclusion of exercise 2.1.5](2.1_exercises.ipynb#5.-If-A,-B-are-arbitrary-m-x-n-matrices,-show-that), we have

$$
AM ^t(B + C) = AM (^tB + ^tC)
$$

And from [theorem 3.1](../2_3_multiplication_of_matrices.ipynb#Theorem-3.1.), we have

$$
AM (^tB + ^tC) = AM ^tB + AM ^tC = \langle A, B \rangle + \langle A, C \rangle
$$

Hence

$$
\langle A, B + C \rangle = \langle A, B \rangle + \langle A, C \rangle
$$

#### SP 3

$$
\langle x A, B \rangle = (x A) M ^tB
$$

And from [theorem 3.1](../2_3_multiplication_of_matrices.ipynb#Theorem-3.1.), we have


$$
(x A) M ^tB = x (A M ^tB) = x \langle A, B \rangle
$$

And

$$
\langle A, x B \rangle = A M ^t (x B)
$$

And from [theorem 3.1](../2_3_multiplication_of_matrices.ipynb#Theorem-3.1.), we have

$$
A M ^t (x B) = x (A M ^t B) = x \langle A, B \rangle
$$

Hence

$$
\langle x A, B \rangle = x \langle A, B \rangle = \langle A, x B \rangle
$$

Q.E.D.

> Give an example of a matrix $M$ and vectors $A, B$ such that $AM ^tB$ is negative (taking $n = 2$).

In [6]:
A = np.matrix([1, 2])
M = np.matrix([[1, 0], [0, 1]])
B = np.matrix([-1, -1])

A * M * np.transpose(B)

matrix([[-3]])

## 11.

(a) Let $A$ be the matrix

$$
\begin{pmatrix}
0 & 1 & 1 \\
0 & 0 & 1 \\
0 & 0 & 0 \\
\end{pmatrix}
$$

Find $A^2 , A^3$. Generalize to $n \times n$ matrices.

### Solution

$$
\begin{equation}
\begin{aligned}
A^2 &= A A \\
&= \begin{pmatrix}
0 & 1 & 1 \\
0 & 0 & 1 \\
0 & 0 & 0 \\
\end{pmatrix}
\begin{pmatrix}
0 & 1 & 1 \\
0 & 0 & 1 \\
0 & 0 & 0 \\
\end{pmatrix} \\
&= \begin{pmatrix}
0 & 0 & 1 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{pmatrix}
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
A^3 &= A A^2 \\
&= \begin{pmatrix}
0 & 1 & 1 \\
0 & 0 & 1 \\
0 & 0 & 0 \\
\end{pmatrix}
\begin{pmatrix}
0 & 0 & 1 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{pmatrix} \\
&= \begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{pmatrix}
\end{aligned}
\end{equation}
$$

In [7]:
A = np.matrix([[0, 1, 1], [0, 0, 1], [0, 0, 0]])
print(A ** 2)
print(A ** 3)

[[0 0 1]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
## Genearlize to 4x4

A = np.matrix([[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0, 0, 0, 0]])

print(A ** 2)
print(A ** 3)
print(A ** 4)

[[0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


(b) Let A be the matrix

$$
\begin{pmatrix}
1 & 1 & 1 \\
0 & 1 & 1 \\
0 & 0 & 1 \\
\end{pmatrix}
$$

Compute $A^2$, $A^3$, $A^4$.

In [9]:
A = np.matrix([[1, 1, 1], [0, 1, 1], [0, 0, 1]])

print(A ** 2)
print(A ** 3)
print(A ** 4)

[[1 2 3]
 [0 1 2]
 [0 0 1]]
[[1 3 6]
 [0 1 3]
 [0 0 1]]
[[ 1  4 10]
 [ 0  1  4]
 [ 0  0  1]]


## 12. Let $X$ be the indicated column vector, and $A$ the indicated matrix. Find $AX$ as a column vector.

(a) $X = \begin{pmatrix} 3 \\ 2 \\ 1 \end{pmatrix}, A = \begin{pmatrix} 1 & 0 & 1 \\ 2 & 0 & 1 \\ 2 & 0 & -1 \end{pmatrix}$

In [10]:
X = np.matrix([[3], [2], [1]])
A = np.matrix([[1, 0, 1], [2, 0, 1], [2, 0, -1]])

A * X

matrix([[4],
        [7],
        [5]])

(b) $X = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}, A = \begin{pmatrix} 2 & 1 & 5 \\ 0 & 1 & 1 \end{pmatrix}$

In [11]:
X = np.matrix([[1], [1], [0]])
A = np.matrix([[2, 1, 5], [0, 1, 1]])

A * X

matrix([[3],
        [1]])

(c) $X = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}, A = \begin{pmatrix} 0 & 1 & 0 \\ 0 & 0 & 0 \end{pmatrix}$

In [12]:
from sympy import Matrix, symbols, init_printing

init_printing()

x_1, x_2, x_3 = symbols('x_1 x_2 x_3')

X = Matrix([[x_1], [x_2], [x_3]])
A = Matrix([[0, 1, 0], [0, 0, 0]])

A * X

⎡x₂⎤
⎢  ⎥
⎣0 ⎦

(d) $X = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}, A = \begin{pmatrix} 0 & 0 & 0 \\ 1 & 0 & 0 \end{pmatrix}$

In [13]:
A = Matrix([[1, 0, 0], [0, 0, 0]])

A * X

⎡x₁⎤
⎢  ⎥
⎣0 ⎦

## 13.

Let

$$
A = \begin{pmatrix}
2 & 1 & 3 \\
4 & 1 & 5
\end{pmatrix}
$$

Find $A X$ for each of the following values of $X$.

$$
\begin{equation}
\begin{aligned}
(a) \ \ \ \ X &= \begin{pmatrix}
1 \\
0 \\
0
\end{pmatrix} &&
(b) \ \ \ \ X &= \begin{pmatrix}
0 \\
1 \\
1
\end{pmatrix} &&
(c) \ \ \ \ X &= \begin{pmatrix}
0 \\
0 \\
1
\end{pmatrix}
\end{aligned}
\end{equation}
$$



In [14]:
A = np.matrix([[2, 1, 3], [4, 1, 5]])

### Solution

For (a):

$$
\begin{equation}
\begin{aligned}
A X &= \begin{pmatrix}
2 & 1 & 3 \\
4 & 1 & 5
\end{pmatrix}
\begin{pmatrix}
1 \\
0 \\
0
\end{pmatrix} \\
&= 1 \begin{pmatrix}
2 \\
4
\end{pmatrix}
+ 0 \begin{pmatrix}
1 \\
1
\end{pmatrix}
+ 0 \begin{pmatrix}
3 \\
5
\end{pmatrix} \\
&= \begin{pmatrix}
2 \\
4
\end{pmatrix}
\end{aligned}
\end{equation}
$$

In [16]:
## Verify with NumPy

X = np.matrix([[1], [0], [0]])

A * X

matrix([[2],
        [4]])

For (b):

$$
\begin{equation}
\begin{aligned}
A X &= \begin{pmatrix}
2 & 1 & 3 \\
4 & 1 & 5
\end{pmatrix}
\begin{pmatrix}
0 \\
1 \\
1
\end{pmatrix} \\
&= 0 \begin{pmatrix}
2 \\
4
\end{pmatrix}
+ 1 \begin{pmatrix}
1 \\
1
\end{pmatrix}
+ 1 \begin{pmatrix}
3 \\
5
\end{pmatrix} \\
&= \begin{pmatrix}
4 \\
6
\end{pmatrix}
\end{aligned}
\end{equation}
$$

In [17]:
X = np.matrix([[0], [1], [1]])

A * X

matrix([[4],
        [6]])

For (c):

$$
\begin{equation}
\begin{aligned}
A X &= \begin{pmatrix}
2 & 1 & 3 \\
4 & 1 & 5
\end{pmatrix}
\begin{pmatrix}
0 \\
0 \\
1
\end{pmatrix} \\
&= 0 \begin{pmatrix}
2 \\
4
\end{pmatrix}
+ 0 \begin{pmatrix}
1 \\
1
\end{pmatrix}
+ 1 \begin{pmatrix}
3 \\
5
\end{pmatrix} \\
&= \begin{pmatrix}
3 \\
5
\end{pmatrix}
\end{aligned}
\end{equation}
$$

In [18]:
X = np.matrix([[0], [0], [1]])

A * X

matrix([[3],
        [5]])

## 16. Let $X$ be a column vector having all its components equal to $0$ except the $i$-th component which is equal to $1$. Let $A$ be an arbitrary matrix, whose size is such that we can form the product $A X$. What is $A X$?

### Solution

$A X$ is be the $i$-th column of $A$.

## 17. Let $A =(a_{i j})$, $i = 1,...,m$ and $j = 1,...,n$ be an $m \times n$ matrix. Let $B =(b_{j k})$, $j = 1, ..., n$ and $k=1, ..., s$ be an $n \times s$matrix. Let $AB = C$. Show that the $k$-th column $C^k$ can be written

$$
C^k = b_{1 k} A^1 + ... + b_{n k} A^n
$$

### Proof

Let $c_{i k}$ be the $i j$-component of $C$. Then we know

$$
c_{i k} = \sum_{j = 1}^{n} a_{i j} b_{j k}
$$

Then the $k$-th column $C^k$ is

$$
\begin{equation}
\begin{aligned}
C^k &= \begin{pmatrix}
c_{1 k} \\
\vdots \\
c_{n k}
\end{pmatrix} \\
&= \begin{pmatrix}
\sum_{j = 1}^{n} a_{1 j} b_{j k} \\
\vdots \\
\sum_{j = 1}^{n} a_{n j} b_{j k} \\
\end{pmatrix} \\
&= \sum_{j = 1}^{n} \begin{pmatrix}
a_{1 j} b_{j k} \\
\vdots \\
a_{n j} b_{j k} \\
\end{pmatrix} \\
&= \sum_{j = 1}^{n} b_{j k} \begin{pmatrix}
a_{1 j} \\
\vdots \\
a_{n j} \\
\end{pmatrix} \\
&= \sum_{j = 1}^{n} b_{j k} A^j \\
&= b_{1 k} A^1 + ... b_{n k} A^n
\end{aligned}
\end{equation}
$$

Q.E.D.

## 18. Let $A$ be a square matrix.

### (a) If $A^2=\mathit{0}$ show that $I - A$ is invertible.

#### Proof

Since $A I = I A = A$, and we have $(- A) I = - A = - (A I) = - (I A) = I (- A)$ by [theorem 3.1](../2_3_multiplication_of_matrices.ipynb#Theorem-3.1.).

Thus from the conclusion of [exercise 4](#4.) we have

$$
(I + A) (I - A) = I^2 - A^2 = I
$$

and

$$
(I - A) (I + A) = (I + (- A)) (I - (- A)) = I^2 - (-A)^2 = I^2 - A^2 = I^2
$$

Hence $I - A$ is invertible and its inverse is $I + A$. Q.E.D.

### (b) If $A^3=\mathit{0}$ show that $I - A$ is invertible.

#### Proof

$$
\begin{equation}
\begin{aligned}
(I - A) (I + A + A^2) &= (I^2 + I A + I A^2) - (A I + A^2 + A^3) \\
&= (I + A + A^2) - (A + A^2 + A^3) \\ 
&= I + (A - A) + (A^2 - A^2) - A^3 \\
&= I
\end{aligned}
\end{equation}
$$

and

$$
\begin{equation}
\begin{aligned}
(I + A + A^2) (I - A) &= (I^2 + A I + A^2 I) - (I A + A^2 + A^3) \\
&= (I + A + A^2) - (A + A^2 + A^3) \\
&= I + (A - A) + (A^2 - A^2) - A^3 \\
&= I
\end{aligned}
\end{equation}
$$

Hence $I - A$ is invertible and its inverse is $I + A + A^2$. Q.E.D.

### (c) In general, if $A^n = 0$ for some positive integer $n$, show that $I - A$ is invertible.

#### Proof

$$
\begin{equation}
\begin{aligned}
(I - A) (I + A + A^2 + ... + A^{n - 1}) &= I (I + A + A^2 + ... + A^{n - 1}) - A (I + A + A^2 + ... + A^{n - 2} + A^{n - 1}) \\
&= (I^2 + I A + I A^2 + ... + I A^{n - 1}) - (A I + A^2 + A^3 + ... + A^{n - 1} + A^n) \\
&= (I + A + A^2 + ... + A^{n - 1}) - (A + A^2 + ... + A^n) \\
&= I - A^n \\
&= I
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
(I + A + A^2 + ... + A^{n - 1}) (I - A) &= (I + A + A^2 + ... + A^{n - 1}) I - (I + A + A^2 + ...+ A^{n - 2} + A^{n - 1}) A \\
&= (I^2 + A I + A^2 I + .. + A^{n - 1} I) - (I A + A^2 + A^3 + ...+ A^{n - 1} + A^n) \\
&= (I + A + A^2 + ... + A^{n - 1}) - (A + A^2 + A^3 + ... + A^{n - 1} + A^n) \\
&= I - A^n \\
&= I
\end{aligned}
\end{equation}
$$

Hence $I - A$ is invertible and its inverse is $I + A + A^2 + ... + A^{n - 1}$. Q.E.D.

### (d) Suppose that $A^2 + 2A + I = \mathit{0}$. Show that $A$ is invertible.

#### Proof

$$
\begin{equation}
\begin{aligned}
A^2 + 2 A + I &= \mathit{0} \\
- A^2 - 2 A &= I \\
- A^2 - 2 A I &= I \\
\end{aligned}
\end{equation}
$$

Hence we have

$$
A (- A - 2 I) = I
$$

and

$$
(- A - 2 I) A = I
$$

Hence $A$ is invertible and its inverse is $(- A - 2 I)$. Q.E.D.

### (e) Suppose that $A^3 - A +I = \mathit{0}$. Show that $A$ is invertible.

#### Proof

$$
\begin{equation}
\begin{aligned}
A^3 - A + I &= \mathit{0} \\
A - A^3 &= I \\
\end{aligned}
\end{equation}
$$

Hence

$$
\begin{equation}
\begin{aligned}
A I - A A^2 &= I \\
A (I - A^2) &= I
\end{aligned}
\end{equation}
$$

and

$$
\begin{equation}
\begin{aligned}
I A - A^2 A &= I \\
(I - A^2) A &= I
\end{aligned}
\end{equation}
$$

Hence $A$ is invertible and its inverse is $I - A^2$. Q.E.D.

## 19.

Let $a, b$ be numbers, and let

$$
\begin{equation}
\begin{aligned}
A = \begin{pmatrix}
1 & a \\
0 & 1
\end{pmatrix}
& & \text{and}& &
B = \begin{pmatrix}
1 & b \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

What is $A B$? What is $A^n$ when $n$ is a positive integer?

### Solution

$$
\begin{equation}
\begin{aligned}
A B &= \begin{pmatrix}
1 & a \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
1 & b \\
0 & 1
\end{pmatrix} \\
&= \begin{pmatrix}
1 & a + b \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Now show 

$$
\begin{equation}
\begin{aligned}
A^n &= \begin{pmatrix}
1 & n a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

**Proof**

We know that

$$
\begin{equation}
\begin{aligned}
A^2 &= \begin{pmatrix}
1 & 2 a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Let $k$ be some positive integer that

$$
\begin{equation}
\begin{aligned}
A^k &= \begin{pmatrix}
1 & k a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

is true. Then we have

$$
\begin{equation}
\begin{aligned}
A A^{k + 1} &= 
\begin{pmatrix}
1 & a \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
1 & k a \\
0 & 1
\end{pmatrix} \\
&= \begin{pmatrix}
1 & (k + 1) a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Hence

$$
\begin{equation}
\begin{aligned}
A^n &= \begin{pmatrix}
1 & n a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Q.E.D.

In [23]:
a, n = symbols('a n')

A = Matrix([[1, a], [0, 1]])

A ** n

⎡1  a⋅n⎤
⎢      ⎥
⎣0   1 ⎦

## 20. Show that the matrix A in Exercise 19 has an inverse. What is this inverse?

### Proof

Let

$$
\begin{equation}
\begin{aligned}
A^{\prime} = \begin{pmatrix}
1 & - a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Then

$$
\begin{equation}
\begin{aligned}
A^{\prime} A &= \begin{pmatrix}
1 & - a \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
1 & a \\
0 & 1
\end{pmatrix} \\
&= \begin{pmatrix}
1 & 0 \\
0 & 1
\end{pmatrix} \\
&= I
\end{aligned}
\end{equation}
$$

and

$$
\begin{equation}
\begin{aligned}
A A^{\prime} &= \begin{pmatrix}
1 & a \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
1 & - a \\
0 & 1
\end{pmatrix} \\
&= \begin{pmatrix}
1 & 0 \\
0 & 1
\end{pmatrix} \\
&= I
\end{aligned}
\end{equation}
$$

Hence $A$ is invertible, and its inverse is

$$
\begin{equation}
\begin{aligned}
A^{\prime} = \begin{pmatrix}
1 & - a \\
0 & 1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

## 21. Show that if $A, B$ are $n \times n$ matrices which have inverses, then $AB$ has an inverse.

Since $A, B$ are $n \times n$ matrices which have inverses, then from the [theorem 3.2](../2_3_multiplication_of_matrices.ipynb#Theorem-3.2.) we have

$$
\begin{equation}
\begin{aligned}
(A B) (B^{-1} A^{-1}) &= A (B B^{-1}) A^{-1} \\
&= A I A^{-1} \\
&= A A^{-1} \\
&= I
\end{aligned}
\end{equation}
$$

and

$$
\begin{equation}
\begin{aligned}
(B^{-1} A^{-1}) (A B) &= B^{-1} (A^{-1} A) B \\
&= B^{-1} I B \\
&= B^{-1} B \\
&= I
\end{aligned}
\end{equation}
$$


Hence $A B$ is invertible, and its inverse is $B^{-1} A^{-1}$. Q.E.D.

## 22. Determine all $2 \times 2$ matrices $A$ such that $A^2 = \mathit{0}$.

### Solution

Let

$$
\begin{equation}
\begin{aligned}
A &= \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
\end{aligned}
\end{equation}
$$

If $A^2 = \mathit{0}$, then we have


$$
\begin{equation}
\begin{aligned}
A^2 &= A A \\
&= \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
&= \begin{pmatrix}
a^2 + b c & a b + b d \\
c a + d c & c b + d^2
\end{pmatrix} \\
&= \begin{pmatrix}
0 & 0 \\
0 & 0
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Hence we have

$$
\begin{cases}
a^2 + b c &= 0 \\
a b + b d &= 0 \\
c a + d c &= 0 \\
c b + d^2 &= 0
\end{cases}
$$

Then we have

$$
\begin{cases}
a^2 &= - b c &= - c b &= d^2 \\
b (a + d) &= c (a + d) &= 0
\end{cases}
$$

**Case 1**: $a = - d$

Then we have

$$
\begin{cases}
a^2 + b c &= 0 \\
a b - b a &= 0 \\
c a - a c &= 0 \\
c b + a^2 &= 0
\end{cases}
$$

As the equations (2) and (3) do not give any more information, we can rewrite the system as

$$
\begin{cases}
a^2 + b c &= 0 \\
c b + a^2 &= 0
\end{cases}
$$

Then we have $b c = - a^2$

**Case 2**: $a = d$

Then we have

$$
\begin{cases}
a^2 + b c &= 0 \\
a b + b a &= 0 \\
c a + a c &= 0 \\
c b + a^2 &= 0
\end{cases}
$$

Then we have

$$
\begin{cases}
b c &= - a^2 \\
a b &= 0 \\
a c &= 0 \\
\end{cases}
$$

If $a = 0$, then as $a = - a = - d$, then we are in case 1.

If $a \neq 0$, then we have

$$
\begin{cases}
b &= 0 \\
c &= 0 \\
b c &= - a^2
\end{cases}
$$

which has no solution.

Hence general form for $A$ that $A^2 = \mathit{0}$ is

$$
A = \begin{pmatrix}
a & b \\
c & -a
\end{pmatrix}
$$

## 23.

Let 

$$
A = \begin{pmatrix}
\cos \theta & - \sin \theta \\
\sin \theta & \cos \theta
\end{pmatrix}
$$

Show that

$$
A^2 = \begin{pmatrix}
\cos 2 \theta & - \sin 2 \theta \\
\sin 2 \theta & \cos 2 \theta
\end{pmatrix}
$$

Determine $A^n$ by induction for any positive integer n.

### Proof

$$
\begin{equation}
\begin{aligned}
A^2 &= A A \\
&= \begin{pmatrix}
\cos \theta & - \sin \theta \\
\sin \theta & \cos \theta
\end{pmatrix}
\begin{pmatrix}
\cos \theta & - \sin \theta \\
\sin \theta & \cos \theta
\end{pmatrix} \\
&= \begin{pmatrix}
(\cos \theta)^2 - (\sin \theta)^2 & (\cos \theta) (- \sin \theta) + (- \sin \theta) (\cos \theta) \\
(\sin \theta) (\cos \theta) + (\cos \theta) (\sin \theta) & - (\sin \theta)^2 + (\cos \theta)^2
\end{pmatrix} \\
&= \begin{pmatrix}
(\cos \theta)^2 - (\sin \theta)^2 & - 2 (\sin \theta) (\cos \theta) \\
2 (\sin \theta) (\cos \theta) & (\cos \theta)^2 - (\sin \theta)^2
\end{pmatrix} \\
&= \begin{pmatrix}
\cos 2 \theta & - \sin 2 \theta \\
\sin 2 \theta & \cos 2 \theta
\end{pmatrix} \\
\end{aligned}
\end{equation}
$$

We now show $A^n$ by induction for any positive integer n.

We have already shown $A^2$ from above.

Let $k$ be some positive integer such that

$$
A^k = \begin{pmatrix}
\cos k \theta & - \sin k \theta \\
\sin k \theta & \cos k \theta
\end{pmatrix}
$$

Then we have

$$
\begin{equation}
\begin{aligned}
A^{k + 1} &= A A^k \\
&= 
\begin{pmatrix}
\cos \theta & - \sin \theta \\
\sin \theta & \cos \theta
\end{pmatrix}
\begin{pmatrix}
\cos k \theta & - \sin k \theta \\
\sin k \theta & \cos k \theta
\end{pmatrix} \\
&= \begin{pmatrix}
- (\sin \theta) (\sin k \theta) + (\cos \theta) (\cos k \theta) & - (\sin \theta) (\cos k \theta) - (\cos \theta) (\sin k \theta) \\
(\sin \theta) (\cos k \theta) + (\cos \theta) (\sin k \theta) & - (\sin \theta) (\sin k \theta) + (\cos \theta) (\cos k \theta) \\
\end{pmatrix} \\
&= \begin{pmatrix}
\cos (k + 1) \theta & - \sin (k + 1) \theta \\
\sin (k + 1) \theta & \cos (k + 1) \theta
\end{pmatrix} \\
\end{aligned}
\end{equation}
$$

Hence for some positive integer $n$, we have

$$
A^n = \begin{pmatrix}
\cos n \theta & - \sin n \theta \\
\sin n \theta & \cos n \theta
\end{pmatrix}
$$

In [40]:
from sympy import cos, sin

theta = symbols('theta')

A = Matrix([[cos(theta), -sin(theta)], [sin(theta), cos(theta)]])
A**2

⎡     2         2                        ⎤
⎢- sin (θ) + cos (θ)   -2⋅sin(θ)⋅cos(θ)  ⎥
⎢                                        ⎥
⎢                          2         2   ⎥
⎣  2⋅sin(θ)⋅cos(θ)    - sin (θ) + cos (θ)⎦

In [44]:
from sympy import simplify

simplify(A ** 2)

⎡cos(2⋅θ)  -sin(2⋅θ)⎤
⎢                   ⎥
⎣sin(2⋅θ)  cos(2⋅θ) ⎦

In [45]:
simplify(A ** 3)

⎡cos(3⋅θ)  -sin(3⋅θ)⎤
⎢                   ⎥
⎣sin(3⋅θ)  cos(3⋅θ) ⎦

In [48]:
k = symbols('k')

A_k = Matrix([[cos(k * theta), -sin(k * theta)], [sin(k * theta), cos(k * theta)]])

A * A_k

⎡-sin(θ)⋅sin(k⋅θ) + cos(θ)⋅cos(k⋅θ)  -sin(θ)⋅cos(k⋅θ) - sin(k⋅θ)⋅cos(θ)⎤
⎢                                                                      ⎥
⎣sin(θ)⋅cos(k⋅θ) + sin(k⋅θ)⋅cos(θ)   -sin(θ)⋅sin(k⋅θ) + cos(θ)⋅cos(k⋅θ)⎦

In [49]:
simplify(A * A_k)

⎡cos(k⋅θ + θ)  -sin(k⋅θ + θ)⎤
⎢                           ⎥
⎣sin(k⋅θ + θ)  cos(k⋅θ + θ) ⎦

## 24. Find a 2 x 2 matrix $A$ such that

$$
A^2 = - I = \begin{pmatrix}
-1 & 0 \\
0 & -1
\end{pmatrix}
$$

### Solution

Let

$$
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$

Since $A^2 = -I$, then we have

$$
\begin{equation}
\begin{aligned}
A^2 &= A A \\
&= \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix} \\
&= \begin{pmatrix}
a^2 + b c & a b + b d \\
c a + d c & c b + d^2
\end{pmatrix} \\
&= \begin{pmatrix}
a^2 + b c & b (a + d) \\
c (a + d) & d^2 + b c
\end{pmatrix}
&= \begin{pmatrix}
-1 & 0 \\
0 & -1
\end{pmatrix}
\end{aligned}
\end{equation}
$$

Then we have

$$
\begin{cases}
a^2 + b c &= -1 \\
b (a + d) &= 0 \\
c (a + d) &= 0 \\
d^2 + b c &= -1
\end{cases}
$$

A solution of the systems of equations is

$$
\begin{cases}
a &= 0 \\
b &= 1 \\
c &= -1
d &= 0
\end{cases}
$$

Which we can write

$$
A = \begin{pmatrix}
0 & 1 \\
-1 & 0
\end{pmatrix}
$$

In [50]:
Matrix([[0, 1], [-1, 0]]) ** 2

⎡-1  0 ⎤
⎢      ⎥
⎣0   -1⎦

## 25.

Let $A$ be an $n \times n$ matrix. Define the **trace** of $A$ to be the sum of the diagonal elements. Thus if $A = (a_{i j})$ then

$$
\operatorname{tr}(A) = \sum_{i = 1}^n a_{i i}
$$

For instance, if

$$
A = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
$$

then $\operatorname{tr}(A) = 1 + 4 = 5$.

If

$$
A = \begin{pmatrix}
1 & -1 & 5 \\
2 & 1 & 3 \\
1 & -4 & 7
\end{pmatrix}
$$

then $\operatorname{tr}(A) = 1 + 1 + 7 = 9$

## 27. Prove in general that if $A, B$ are square $n \times n$ matrices, then

$$
\operatorname{tr}(A B) = \operatorname{tr}(B A)
$$

### Proof

Let $A$ = $(a_{i j})$ and $B = (b_{i j})$ for $i = 1, ..., n$ and $j = 1, ..., n$.

Let $C = A B = (c_{i j})$ for $i = 1, ..., n$ and $j = 1, ..., n$.

Let $C^{\prime} = A B = (c^{\prime}_{j i})$ for $j = 1, ..., n$ and $i = 1, ..., n$.

Then we know the diagonal elements of $C = A B$ are

$$
\{c_{i i} = \sum_{j = 1}^n a_{i j} b_{j i} \}
$$

for $i = 1, ..., n$.

Hence

$$
\operatorname{tr}(C) = \sum_{i = 1}^n \sum_{j = 1}^n a_{i j} b_{j i}
$$

Similarly, the diagonal elements of $C = B A$ are

$$
\{c^{\prime}_{j j} = \sum_{i = 1}^n b_{j i} a_{i j} \}
$$

for $j = 1, ..., n$.

Hence

$$
\operatorname{tr}(C^{\prime}) = \sum_{j = 1}^n \sum_{i = 1}^n b_{j i}a_{i j}
$$

Then we have

$$
\operatorname{tr}(A B) = \operatorname{tr}(C) = \sum_{i = 1}^n \sum_{j = 1}^n a_{i j} b_{j i} = \sum_{j = 1}^n \sum_{i = 1}^n a_{i j} b_{j i} = \sum_{j = 1}^n \sum_{i = 1}^n b_{j i}a_{i j} = \operatorname{tr}(C^{\prime}) = \operatorname{tr}(B A)
$$

Q.E.D.

## 28. For any square matrix $A$, show that $\operatorname{tr}(A) = \operatorname{tr}(^tA)$.

### Proof

Let $A = (a_{i j})$ and $^tA = (a^{\prime}_{i j})$, for $i = 1, ..., n$ and $j = 1, ..., n$.

Then we have $a^{\prime}_{j i} = a_{i j}$.

Hence 

$$
\operatorname{tr}(A) = \sum_{i = 1}^n a_{i i} = \operatorname{tr}(^tA)
$$

Q.E.D.

## 30.

Let

$$
A = \begin{pmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{pmatrix}
$$

Find $A^2, A^3, A^4$.

In [59]:
A = Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

A ** 2

⎡1  0  0⎤
⎢       ⎥
⎢0  4  0⎥
⎢       ⎥
⎣0  0  9⎦

In [60]:
A ** 3

⎡1  0  0 ⎤
⎢        ⎥
⎢0  8  0 ⎥
⎢        ⎥
⎣0  0  27⎦

In [61]:
A ** 4

⎡1  0   0 ⎤
⎢         ⎥
⎢0  16  0 ⎥
⎢         ⎥
⎣0  0   81⎦

## 30. Let $A$ be a diagonal matrix, with diagonal elements $a_1, ... ,a_n$. What is $A^2, A^3, A^k$ for any positive integer $k$?

### Solution

$A^k$ is a diagonal matrix with diagonal elements $a_1^k, ..., a_n^k$.

## 31.

Let

$$
A = \begin{pmatrix}
0 & 1 & 6 \\
0 & 0 & 4 \\
0 & 0 & 0
\end{pmatrix}
$$

Find $A^3$

In [62]:
A = Matrix([[0, 1, 6], [0, 0, 4], [0, 0, 0]])

A **3

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

## 32. 

Let $A$ be an invertible $n \times n$ matrix. Show that

$$
^t(A^{-1}) = (^tA)^{-1}
$$

We may therefore write $^tA^{-1}$ without fear of confusion.

### Proof

From [theorem 3.3](../2_3_multiplication_of_matrices.ipynb#Theorem-3.3.) we have

$$
^t(A^{-1}) ^tA = ^t(A A^{-1}) = ^t I = I
$$

and

$$
^tA ^t(A^{-1}) = ^t (A^{-1} A) = ^t I = I
$$

Hence 

$$
^t(A^{-1}) = (^t A)^{-1}
$$

Q.E.D.

## 33. 

Let $A$ be a complex matrix, $A = (a_{i j})$ , and let $\overline{A} = (\overline{a_{i j}})$ where the bar means
complex conjugate. Show that

$$
^t(\overline{A}) = \overline{^tA}
$$

We then write simply $^t\overline{A}$.

## 34.

Let $A$ be a diagonal matrix:

$$
A = \begin{pmatrix}
a_1 & 0 & ... & 0 \\
0 & a_2 & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & a_n \\
\end{pmatrix}
$$


If $a_i = 0$ for all $i$, show that $A$ is invertible. What is its inverse?

### Solution

Let 

$$
A^{\prime} = \begin{pmatrix}
\frac{1}{a_1} & 0 & ... & 0 \\
0 & \frac{1}{a_2} & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & \frac{1}{a_n} \\
\end{pmatrix}
$$

Then

$$
\begin{equation}
\begin{aligned}
A^{\prime} A &= \begin{pmatrix}
\frac{1}{a_1} & 0 & ... & 0 \\
0 & \frac{1}{a_2} & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & \frac{1}{a_n} \\
\end{pmatrix}
\begin{pmatrix}
a_1 & 0 & ... & 0 \\
0 & a_2 & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & a_n \\
\end{pmatrix} \\
&= \begin{pmatrix}
1 & 0 & ... & 0 \\
0 & 1 & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & 1 \\
\end{pmatrix} \\
&= I
\end{aligned}
\end{equation}
$$

$$
\begin{equation}
\begin{aligned}
A A^{\prime} &= \begin{pmatrix}
a_1 & 0 & ... & 0 \\
0 & a_2 & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & a_n \\
\end{pmatrix}
\begin{pmatrix}
\frac{1}{a_1} & 0 & ... & 0 \\
0 & \frac{1}{a_2} & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & \frac{1}{a_n} \\
\end{pmatrix}\\
&= \begin{pmatrix}
1 & 0 & ... & 0 \\
0 & 1 & ... & 0 \\
\vdots & \vdots & & \vdots \\
0 & 0 & ... & 1 \\
\end{pmatrix} \\
&= I
\end{aligned}
\end{equation}
$$

Hence $A$ is invertible and $A^{-1} = A^\prime$.

In [67]:
a_1, a_2, a_3, a_4 = symbols('a1:5')

A = Matrix([[a_1, 0, 0, 0], [0, a_2, 0, 0], [0, 0, a_3, 0], [0, 0, 0, a_4]])
A_prime = Matrix([[1 / a_1, 0, 0, 0], [0, 1 / a_2, 0, 0], [0, 0, 1 / a_3, 0], [0, 0, 0, 1 / a_4]])

A * A_prime

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

## 35.

Let $A$ be a strictly upper triangular matrix, i.e. a square matrix $(a_{i j})$ having all its components below and on the diagonal equal to $0$. We may express this by writing $a_{i j} = 0$ if $i \geq j$.

$$
A = \begin{pmatrix}
0 & a_{1 2} & a_{1 3} & ... & a_{1 n} \\
0 & 0 & a_{2 3} & ... & a_{2 n} \\
\vdots & \vdots & \vdots & & \vdots \\
0 & 0 & 0 & ... & a_{n - 1 \  n} \\
0 & 0 & 0 & ... & 0 \\
\end{pmatrix}
$$

Prove that $A^n = \mathit{0}$. (If you wish, you may do it only in case $n = 2, 3$ and $4$. The general case can be done by induction.)

### Proof

