## 1. In each one of the following cases, find $M_{\mathscr{B}^\prime}^\mathscr{B}(id)$. The vector space in each case is $R^3$.

### (a) 

$$
\mathscr{B} = \{ \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}, \begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix}, \begin{pmatrix} 0 \\ 1 \\ 2 \end{pmatrix} \} \\
\mathscr{B}^\prime = \{ \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix}, \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix}, \begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix} \}
$$

#### Solution

Let $(a_{i j})$ such that

$$
\operatorname{id}(\begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}) = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix} = a_{1 1} \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix} + a_{2 1} \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix} + a_{3 1} \begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix} \\
\operatorname{id}(\begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix}) = \begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix} = a_{1 2} \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix} + a_{2 2} \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix} + a_{3 2} \begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix} \\
\operatorname{id}(\begin{pmatrix} 0 \\ 1 \\ 2 \end{pmatrix}) = \begin{pmatrix} 0 \\ 1 \\ 2 \end{pmatrix} = a_{1 3} \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix} + a_{2 3} \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix} + a_{3 3} \begin{pmatrix} -1 \\ 1 \\ 1 \end{pmatrix} \\
$$

Then we have

In [55]:
import numpy as np
from scipy.linalg import solve

A = np.matrix([[2, 0, -1], [1, 0, 1], [1, 1, 1]])
y_1 = np.matrix([[1, 1, 0]]).T
solve(A, y_1)

# a_11 = 2/3, a_21 = -1, a_31 = 1/3

array([[ 0.66666667],
       [-1.        ],
       [ 0.33333333]])

In [25]:
y_2 = np.matrix([[-1, 1, 1]]).T
solve(A, y_2)

# a_12 = 0, a_22 = 0, a_32 = 1

array([[0.],
       [0.],
       [1.]])

In [28]:
y_3 = np.matrix([[0, 1, 2]]).T
solve(A, y_3)

# a_13 = 1/3, a_23 = 1, a_33 = 2/3

array([[0.33333333],
       [1.        ],
       [0.66666667]])

Thus

$$
M_{\mathscr{B}^\prime}^\mathscr{B}(id) = \begin{pmatrix} a_{1 1} & a_{1 2} & a_{1 3} \\ a_{2 1} & a_{2 2} & a_{2 3} \\ a_{3 1} & a_{3 2} & a_{3 3} \end{pmatrix} = \begin{pmatrix} \frac{2}{3} & 0 & \frac{1}{3} \\ -1 & 0 & 1 \\ \frac{1}{3} & 1 & \frac{2}{3} \end{pmatrix}
$$

## 2. Let $L: V \to V$ be a linear map. Let $\mathscr{B} = \{v_1, ..., v_n \}$ be a basis of $V$. Suppose that there are numbers $c_1, ..., c_n$ such that $L(v_i) = c_i v_i$ for $i=1,...,n$. What is $M_\mathscr{B}^\mathscr{B}(L)$?

### Solution

Since $\mathscr{B} = \{v_1, ..., v_n \}$ is a basis of $V$, and

$$
L(v_i) = c_i v_i
$$

Then we have

$$
M_\mathscr{B}^\mathscr{B}(L) = \begin{pmatrix} \phi_\mathscr{B}(L(v_1)) & \cdots & \phi_\mathscr{B}(L(v_n)) \end{pmatrix} = \begin{pmatrix} \phi_\mathscr{B}(c_1 v_1) & \cdots & \phi_\mathscr{B}(c_i v_i) \end{pmatrix}
= \begin{pmatrix} \begin{pmatrix} c_1 \\ 0 \\ \vdots \\ 0 \end{pmatrix} & \begin{pmatrix} 0 \\ c_2 \\ \vdots \\ 0 \end{pmatrix} & \cdots \begin{pmatrix} 0 \\ 0 \\ \vdots \\ c_n \end{pmatrix} \end{pmatrix}
= \begin{pmatrix} c_1 & 0 & \cdots & 0 \\ 0 & c_2 & \cdots & 0 \\ \vdots & \vdots & \cdots & \vdots \\ 0 & 0 & \cdots & c_n \end{pmatrix}
$$

## 3.

For each real number $\theta$, let $F_\theta: R^2 \to R^2$ be the linear map represented by the matrix

$$
R(\theta) = \begin{pmatrix} \cos \theta & - \sin \theta \\ \sin \theta & \cos \theta \end{pmatrix}
$$

Show that if $\theta, \theta^\prime$ are real numbers, then $F_\theta F_{\theta^\prime} = F_{\theta + \theta^\prime}$ (You must use the addition formula for sine and cosine.) Also show that $F_\theta^{-1} = F_{-\theta}$.

### Proof

#### Proof: $F_\theta F_{\theta^\prime} = F_{\theta + \theta^\prime}$

Since $\theta, \theta^\prime$ are real numbers, we have

$$
\cos (\theta + \theta^\prime) = \cos \theta \cos \theta^\prime - \sin \theta \sin \theta^\prime \\
\sin (\theta + \theta^\prime) = \sin \theta \cos \theta^\prime + \cos \theta \sin \theta^\prime
$$

Then we have

In [43]:
from sympy import symbols, Matrix, cos, sin, simplify, init_printing

init_printing()

theta, theta_prime = symbols('\\theta \\theta^\prime')

R = lambda x: Matrix([[cos(x), -sin(x)], [sin(x), cos(x)]])

product = R(theta) * R(theta_prime)

product

⎡-sin(\theta)⋅sin(\theta__\′) + cos(\theta)⋅cos(\theta__\′)  -sin(\theta)⋅cos(
⎢                                                                             
⎣sin(\theta)⋅cos(\theta__\′) + sin(\theta__\′)⋅cos(\theta)   -sin(\theta)⋅sin(

\theta__\′) - sin(\theta__\′)⋅cos(\theta)⎤
                                         ⎥
\theta__\′) + cos(\theta)⋅cos(\theta__\′)⎦

In [44]:
simplify(product)

⎡cos(\theta + \theta__\′)  -sin(\theta + \theta__\′)⎤
⎢                                                   ⎥
⎣sin(\theta + \theta__\′)  cos(\theta + \theta__\′) ⎦

Thus we have

$$
F_\theta F_{\theta^\prime} = F_{\theta + \theta^\prime}
$$

### Proof: $F_\theta^{-1} = F_{-\theta}$

In [47]:
simplify(R(-theta) * R(theta))

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

In [48]:
simplify(R(theta) * R(-theta))

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

Thus

$$
F_{-\theta} F_{\theta} = I = F_{\theta} F_{-\theta}
$$

Thus

$$
F_{\theta}^{-1} = F_{-\theta}
$$

## 5. Let $X = \begin{pmatrix}1 \\ 2\end{pmatrix}$ be a point of the plane. Let F be the rotation through an angle of $\frac{\pi}{4}$. What are the coordinates of $F(X)$ relative to the usual basis $\{E^1,E^2\}$?

### Solution

In [49]:
from sympy import pi

X = Matrix([[1, 2]]).T

R(pi / 4) * X

⎡-√2 ⎤
⎢────⎥
⎢ 2  ⎥
⎢    ⎥
⎢3⋅√2⎥
⎢────⎥
⎣ 2  ⎦

## 6. Same question when $X = \begin{pmatrix} -1 \\ 3 \end{pmatrix}$, and F is the rotation through $\frac{\pi}{2}$.

### Solution

In [50]:
X = Matrix([[-1, 3]]).T

R(pi / 2) * X

⎡-3⎤
⎢  ⎥
⎣-1⎦

## 7. In general, let $F$ be the rotation through an angle $\theta$. Let $\begin{pmatrix}x \\ y\end{pmatrix}$ be a point of the plane in the standard coordinate system. Let $\begin{pmatrix} x^\prime \\ y^\prime \end{pmatrix}$ be the coordinates of this point in the rotated system. Express $x^\prime, y^\prime$ in terms of $x, y$, and $\theta$.

### Solution

In [53]:
x, y, x_prime, y_prime = symbols('x y x^prime y^\prime')

X = Matrix([[x, y]]).T
R(theta) * X

⎡x⋅cos(\theta) - y⋅sin(\theta)⎤
⎢                             ⎥
⎣x⋅sin(\theta) + y⋅cos(\theta)⎦

## 8. In each of the following cases, let $D = \frac{d}{d t}$ be the derivative. We give a set of linearly independent functions $\mathscr{B}$. These generate a vector space $V$, and $D$ is a linear map from $V$ into itself. Find the matrix associated with $D$ relative to the bases $\mathscr{B}, \mathscr{B}$ ($M_\mathscr{B}^\mathscr{B}(D)$).

### (a) $\{e^t, e^{2t}\}$

#### Solution

Since $\mathscr{B} = \{e^t, e^{2t}\}$ is a basis of $V$, then we have $\phi_\mathscr{B}: V \xrightarrow{\simeq} K^2$ defined as

$$
\phi_\mathscr{B}(e^t) = \begin{pmatrix} 1 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(e^{2t}) = \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$$

Then we have

$$
\begin{aligned}
M_\mathscr{B}^\mathscr{B}(D) &= \begin{pmatrix} \phi_\mathscr{B}(D(e^t)) & \phi_\mathscr{B}(D(e^{2t})) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(e^t) & \phi_\mathscr{B}(2 e^{2t}) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(e^t) & 2 \phi_\mathscr{B}(e^{2t}) \end{pmatrix} \\
&= \begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}
\end{aligned}
$$

### (b) $\{1, t\}$

### Solution

Since $\mathscr{B} = \{1, t\}$ is a basis of $V$, then we have $\phi_\mathscr{B}: V \xrightarrow{\simeq} K^2$ defined as

$$
\phi_\mathscr{B}(1) = \begin{pmatrix} 1 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(t) = \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$$

And since $\phi_\mathscr{B}$ is a linear map, we have

$$
\phi_\mathscr{B}(0) = \begin{pmatrix} 0 \\ 0 \end{pmatrix}
$$

Then we have

$$
\begin{aligned}
M_\mathscr{B}^\mathscr{B}(D) &= \begin{pmatrix} \phi_\mathscr{B}(D(1)) & \phi_\mathscr{B}(D(t)) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(0) & \phi_\mathscr{B}(1) \end{pmatrix} \\
&= \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix}
\end{aligned}
$$

### (c) $\{e^t, te^t\}$

#### Solution

Since $\mathscr{B} = \{e^t, te^t\}$ is a basis of $V$, then we have $\phi_\mathscr{B}: V \xrightarrow{\simeq} K^2$ defined as

$$
\phi_\mathscr{B}(e^t) = \begin{pmatrix} 1 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(t e^t) = \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$$

Then we have

$$
\begin{aligned}
M_\mathscr{B}^\mathscr{B}(D) &= \begin{pmatrix} \phi_\mathscr{B}(D(e^t)) & \phi_\mathscr{B}(D(te^t)) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(e^t) & \phi_\mathscr{B}(e^t + t e^t) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(e^t) & \phi_\mathscr{B}(e^t) + \phi_\mathscr{B}(t e^t) \end{pmatrix} \\
&= \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}
\end{aligned}
$$

### (d) $\{1, t, t^2\}$

Since $\mathscr{B} =\{1, t, t^2\}$ is a basis of $V$, then we have $\phi_\mathscr{B}: V \xrightarrow{\simeq} K^3$ defined as

$$
\phi_\mathscr{B}(1) = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(t) = \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(t^2) = \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix} \\
$$

And since $\phi_\mathscr{B}$ is a linear map, we have

$$
\phi_\mathscr{B}(0) = \begin{pmatrix} 0 \\ 0 \\ 0 \end{pmatrix}
$$

Then we have

$$
\begin{aligned}
M_\mathscr{B}^\mathscr{B}(D) &= \begin{pmatrix} \phi_\mathscr{B}(D(1)) & \phi_\mathscr{B}(D(t)) & \phi_\mathscr{B}(D(t^2)) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(0) & \phi_\mathscr{B}(1) & \phi_\mathscr{B}(2 t) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(0) & \phi_\mathscr{B}(1) & 2 \phi_\mathscr{B}(t) \end{pmatrix} \\
&= \begin{pmatrix} 0 & 1 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \end{pmatrix}
\end{aligned}
$$

### (e) $\{1, t, e^t, e^{2t}, te^{2t}\}$

#### Solution

Since $\mathscr{B} = \{1, t, e^t, e^{2t}, te^{2t}\}$ is a basis of $V$, then we have $\phi_\mathscr{B}: V \xrightarrow{\simeq} K^5$ defined as

$$
\phi_\mathscr{B}(1) = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(t) = \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(e^t) = \begin{pmatrix} 0 \\ 0 \\ 1 \\ 0 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(e^{2t}) = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 1 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(te^{2t}) = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \\ 1 \end{pmatrix} \\
$$

Then we have

$$
\begin{aligned}
M_\mathscr{B}^\mathscr{B}(D) &= \begin{pmatrix} \phi_\mathscr{B}(D(1)) & \phi_\mathscr{B}(D(t)) & \phi_\mathscr{B}(D(e^t)) & \phi_\mathscr{B}(D(e^{2t})) & \phi_\mathscr{B}(D(te^{2t})) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(0) & \phi_\mathscr{B}(1) & \phi_\mathscr{B}(e^t) & \phi_\mathscr{B}(2 e^{2t}) & \phi_\mathscr{B}(e^{2t} + 2 t e^{2 t}) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(0) & \phi_\mathscr{B}(1) & \phi_\mathscr{B}(e^t) & 2 \phi_\mathscr{B}(e^{2t}) & \phi_\mathscr{B}(e^{2t}) + 2 \phi_\mathscr{B}(t e^{2 t}) \end{pmatrix} \\
&= \begin{pmatrix} 0 & 1 & 0 & 0 & 0  \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 & 0\\ 0 & 0 & 0 & 2 & 1 \\ 0 & 0 & 0 & 0 & 2\end{pmatrix}
\end{aligned}
$$

### (f) $\{\sin t, \cos t\}$

#### Solution

Since $\mathscr{B} = \{\sin t, \cos t\}$ is a basis of $V$, then we have $\phi_\mathscr{B}: V \xrightarrow{\simeq} K^2$ defined as

$$
\phi_\mathscr{B}(\sin t) = \begin{pmatrix} 1 \\ 0 \end{pmatrix} \\
\phi_\mathscr{B}(\cos t) = \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$$

Then we have

$$
\begin{aligned}
M_\mathscr{B}^\mathscr{B}(D) &= \begin{pmatrix} \phi_\mathscr{B}(D(\sin t)) & \phi_\mathscr{B}(D(\cos t)) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(\cos t) & \phi_\mathscr{B}(- \sin t) \end{pmatrix} \\
&= \begin{pmatrix} \phi_\mathscr{B}(\cos t) & - \phi_\mathscr{B}(\sin t) \end{pmatrix} \\
&= \begin{pmatrix} 0 & -1 \\ 1 & 0 \end{pmatrix}
\end{aligned}
$$

## 9

### (a)  Let $N$ be a square matrix. We say that $N$ is **nilpotent** if there exists a positive integer $r$ such that $N^r = \mathit{0}$. Prove that if $N$ is nilpotent, then $I - N$ is invertible.

#### Proof

Since $N$ is nilpotent, by definition there are some positive integer $r$ such that

$$
N^r = \mathit{0}
$$


Then we have

$$
\begin{aligned}
(I - N) (I + N + ... + N^{r - 1}) &= I (I + N + ... + N^{r - 1}) - N (I + N + ... + N^{r - 1}) \\
&= (I + N + ... + N^{r - 1}) - (N + N^2 + ... + N^r) \\
&= I - N^r \\
&= I - \mathit{0} \\
&= I
\end{aligned}
$$

and

$$
\begin{aligned}
(I + N + ... + N^{r - 1}) (I - N) &= (I + N + ... + N^{r - 1}) I - (I + N + ... + N^{r - 1}) N \\
&= (I + N + ... + N^{r - 1}) - (N + N^2 + ... + N^r) \\
&= I - N^r \\
&= I - \mathit{0} \\
&= I
\end{aligned}
$$


Thus $I - N$ is invertible and $(I - N)^{-1} = I + N + ... + N^{r - 1}$. Q.E.D.

### (b) State and prove the analogous statement for linear maps of a vector space into itself.

#### Statement

Let $F: V \to V$ be a linear map. We say $F$ is **nilpotent** if there exists some positive integer $r$ such that $F^r = \mathit{0}$. Prove that if $F$ is nilpotent, then $\operatorname{id} - F$ is invertible.

##### Proof

Since $F$ is nilpotent, there exists some positive integer $r$ such that

$$
F^r = \mathit{0}
$$

And by [theorem 4.2 in chapter 3.4](./3_linear_mappings/3_4_composition_and_inverse_of_linear_mappings.ipynb#Theorem-4.2.-Algebraic-rules-for-linear-map-compositions) we have

$$
\begin{aligned}
(I - F) (I + F + F^2 + ... F^{r - 1}) &= I (I + F + F^2 + ... F^{r - 1}) - F (I + F + F^2 + ... F^{r - 1}) \\
&= (I + F + F^2 + ... F^{r - 1}) - (F + F^2 + ... + F^r) \\
&= I - F^r \\
&= I - \mathit{0} \\
&= I
\end{aligned}
$$

and

$$
\begin{aligned}
(I + F + F^2 + ... F^{r - 1}) (I - F) &= (I + F + F^2 + ... F^{n - 1}) I - (I + F + F^2 + ... F^{r - 1}) F \\
&= (I + F + F^2 + ... F^{n - 1}) - (F + F^2 + ... F^r) \\
&= I - F^r \\
&= I - \mathit{0} \\
&= I
\end{aligned}
$$

Q.E.D.

## 10. Let $P_n$ be the vector space of polynomials of degree $\leq n$. Then the derivative $D: P_n \to P_n$ is a linear map of $P_n$ into itself. Let I be the identity mapping. Prove that the following linear maps are invertible:

### (a) $I - D^2$.

#### Proof

Since $P_n$ is the vector space of polynomial of degree $\leq n$, we know that for any $p \in P_n$, $D^{n + 1}(p) = 0$. Thus $D^{n + 1} = \mathit{0}$.

Then we have $(D^{n + 1})^2 = (D^2)^{n + 1} = \mathit{0}$. Thus by definition $D^2$ is nilpotent.

Then by [the conclusion of exercise 9](#9), $I - D^2$is invertible.