# 4.1 The linear map associated with a matrix

Let $A$ be any $m \times n$ matrix on field $K$ which is defined as

We can associate $A$ a map

$$
L_A: K^n \to K^m
$$

by letting

$$
L_A(X) = A X
$$

for every column $X \in K^n$.

## Linearity of the associated map

Let $X, Y$ be any column vector in $K^n$, and $c$ be any number in $K$. By [theorem 3.1 in chapter 2](../2_matrices/2_3_multiplication_of_matrices.ipynb#Theorem-3.1.), we know

$$
L(X + Y) = A (X + Y) = A X + A Y = L(X) + L(Y)
$$

$$
L(c X) = A (c X) = c (A X) = c L(X)
$$

Thus $L$, the map associated to matrix $A$, is linear.

We call $L_A$ the linear map **associated** with the matrix $A$.

## Theorem 1.1. Uniqueness of associated matrix to a linear map

If $A, B$ are $m \times n$ matrices and if $L_A = L_B$, then $A = B$. In other words, if matrices $A, B$ give rise to the same linear map, then they are equal.

### Proof

Let $X$ be any column vector in $K^n$. By the definition of associated linear map, we have

$$
L_A(X) = A X \\
L_B(X) = B X
$$

Since

$$
L_A = L_B
$$

Then

$$
A X = B X
$$

And since $K^m$ is vector space, there exists [a unique addition inverse](../1_vector_spaces/exercise/1.1_exercise.ipynb#4.-Let-$V$-be-a-vector-space,-and-$v,-w$-two-elements-of-$V$.-If-$v-+-w-=-\mathit{0}$,-show-that-$w-=---v$.) in $K^m$ for $B X$.

And since [a matrices space is a vector space](../2_matrices/2_1_matrices_spaces.ipynb#Matrix-space-as-a-vector-space), similarly $- B$ is the unique addition inverse for $B$. And by the definition of matrix multiplication, $(- B) X = - (B X)$. Thus $(- B) X$ is the unique addition inverse for $B X$ in $K^m$. Then we can write

$$
A X + (- B) X = B X + (- B) X = \mathit{0}
$$

And again by [theorem 3.1 in chapter 2](../2_matrices/2_3_multiplication_of_matrices.ipynb#Theorem-3.1.) we have

$$
(A + (- B)) X = \mathit{0}
$$

Hence $A$ is the additive inverse of $(- B)$ in $K^m$. And again since additive inverse is unique in a vector space, we have $A = B$. Q.E.D.

## System of homogeneous linear equations and associated linear maps

By the definition of matrix-column-vector-multiplication, we can write a [system of homogeneous linear equations]()

$$
\begin{array}{c}
a_{1 1} x_1 + ... + a_{1 n} x_n &= 0 \\
...  \\
a_{m 1} x_1 + ... + a_{m n} x_n &= 0 \\
\end{array}
$$

as

$$
A X = \mathit{0}
$$

for a $m \times n$ matrix $A$ defined as

$$
A = \begin{pmatrix}
a_{1 1} & \cdots & a_{1 n} \\
\vdots & & \vdots \\
a_{m 1} & \dots & a_{m n}
\end{pmatrix}
$$

and for some $X \in K^n$.

And thus we can see *the set of solutions of the system of homogeneous linear equations as the kernel of its associated linear map*.

# 4.2 The matrix associated with a linear map

## Special case: $L: K^n \to K$

Let $L: K^n \to K$ be a linear map. There exists a unique vector $A$ in $K^n$ such that $L = L_A$, i.e. such that for all $X$ we have

$$
L(X) = A \cdot X
$$

### Proof

Let $E^1, ..., E^n$ be the unit column vectors of $K^n$. Then any column vector in $K^n$ can be written as $X = \begin{pmatrix} x_1 \\ \vdots \\ x_n \end{pmatrix} = x_1 E^1 + ... + x_n E^n$ for some $x_1, ..., x_n \in K$.

Then since $L$ is a linear map, we have

$$
L(X) = L(x_1 E^1 + ... + x_n E^n) = x_1 L(E^1) + ... + x_n L(E^n)
$$

Now we let

$$
A = (L(E^1), ..., L(E^n))
$$

Then

$$
L(X) = x_1 L(E^1) + ... + x_n L(E^n) = A \cdot X = L_A(X)
$$

Now we have proven the matrix $A$ such that $L = L_A$ exists. And by [theorem 1.1](#Theorem-1.1.-Associated-linear-maps-equality-implies-matrices-equality) we know such $A$ is unique. Q.E.D.

## Theorem 2.1: Generalization:  $L: K^n \to K^m$

Let $L: K^n \to K^m$ be a linear map. Then there exists a unique matrix $A$ such that $L = L_A$.

### Proof

Let $E^1, ..., E^n$ be the unit column vectors of $K^n$. And let $e^1, ..., e^m$ be the unit column vectors of $K^m$. Then we can write any $X \in F^n$ as

$$
X = \begin{pmatrix}
x_1 \\
\vdots \\
x_n
\end{pmatrix} = x_1 E^1 + ... + x_n E^n
$$

And since $L$ is a linear map, we have

$$
L(X) = L(x_1 E^1 + ... + x_n E^n) = x_1 L(E^1) + ... + x_n L(E^n)
$$

And since $e^1, ..., e^m$ are column unit vectors in $F^m$, then there exist numbers $a_{i j}$ for $i$ in $1, ..., m$ and $j$ in $1, ..., n$ such that

$$
\begin{aligned}
L(E^1) &= a_{1 1} e^1 + \cdots + a_{m 1} e^m \\
& \vdots  \\
L(E^n) &= a_{1 n} e^1 + \cdots + a_{m n} e^m \\
\end{aligned}
$$

or in terms of column vectors,

$$
L(E^1) = \begin{pmatrix}a_{1 1} \\ \vdots \\ a_{m 1}\end{pmatrix}, \cdots, L(E^n) = \begin{pmatrix}a_{1 n} \\ \vdots \\ a_{m n}\end{pmatrix}
$$

Hence

$$
\begin{aligned}
L(X) &= x_1 (a_{1 1} e^1 + ... + a_{m 1} e^m) + ... + x_n (a_{1 n} e^1 + ... + a_{m n} e^m) \\
&= (a_{1 1} x_1 + ... + a_{1 n} x_n) e^1 + ... + (a_{m 1} x_1 + ... + a_{m n} x_n) e^m \\
\end{aligned}
$$

Hence if we let $A = (a_{i j})$, then we can write

$$
L(X) = A X
$$

Written in full, this reads

$$
\begin{pmatrix}
a_{1 1} & \cdots & a_{1 n} \\
\vdots & & \vdots \\
a_{m 1} & \cdots & a_{m n} \\
\end{pmatrix}
\begin{pmatrix}
x_1 \\
\vdots \\
x_n
\end{pmatrix}
=
\begin{pmatrix}
a_{1 1} x_1 + ... + a_{1 n} x_n \\
\vdots \\
a_{m 1} x_1 + ... + a_{m n} x_n
\end{pmatrix}
$$

Hence $L = L_A$ is the linear map associated with the matrix $A$.

We then define $A$ is the **associated matrix** with the linear map $L$. By [theorem 1.1](#Theorem-1.1.-Associated-linear-maps-equality-implies-matrices-equality), we know such an associated matrix $A$ to $L$ is unique. Q.E.D.

## Examples

### Example 1.

Let $F: R^3 \to R^2$ be the projection, in other words the mapping such that $F(x_1, x_2, x_3) = (x_1, x_2)$.

Then the matrix associated with $F$ is

$$
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0
\end{pmatrix}
$$

### Example 2.

Let $I: R^n \to R^n$ be the identity. Then the matrix associated with $I$ is the matrix

$$
\begin{pmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & 1 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & & \vdots \\
0 & 0 & 0 & \cdots & 1
\end{pmatrix}
$$

which is the identity matrix.

### Example 3.

According to [theorem 2.1 of chapter 3](../3_linear_mappings/3_2_linear_mappings.ipynb#Theorem-2.1:-Linear-mappings-and-basis), let $E^1, ..., E^4$ be the unit column vector of $R^4$, there exists a unique linear map $L: R^4 \to R^2$ such that

$$
L(E^1) = \begin{pmatrix}2 \\ 1\end{pmatrix}, L(E^2) = \begin{pmatrix}3 \\ -1\end{pmatrix}, L(E^3) = \begin{pmatrix}-5 \\ 4\end{pmatrix}, L(E^4) = \begin{pmatrix}1 \\ 7\end{pmatrix}
$$

Let $e_1, e_2$ be the unit vectors of $R^2$. Then we have

$$
\begin{array}{l}
L(E^1) &= \begin{pmatrix}2 \\ 1\end{pmatrix} &= 2 e_1 + 1 e_2 \\
L(E^2) &= \begin{pmatrix}3 \\ -1\end{pmatrix} &= 3 e_1 + (-1) e_2 \\
L(E^3) &= \begin{pmatrix}-5 \\ 4\end{pmatrix} &= -5 e_1 + 4 e_2 \\
L(E^4) &= \begin{pmatrix}1 \\ 7\end{pmatrix} &= 1 e_1 + 7 e_2
\end{array}
$$

Let there be any $X \in R^4$. We can then write $X$ as a linear combination of the unit vectors in $R^4$. Thus there exist some numbers $x_1, x_2, x_3, x_4 \in R$ such that

$$
X = x_1 E^1 + x_2 E^2 + x_3 E^3 + x_4 E^4
$$

From the linearity of $L$, we have

$$
\begin{aligned}
L(X) &= L(x_1 E^1 + x_2 E^2 + x_3 E^3 + x_4 E^4) \\
&= x_1 L(E^1) + x_2 L(E^2) + x_3 L(E^3) + x_4 L(E^4) \\
&= x_1 (2 e^1 + 1 e^2) + x_2 (3 e^1 + (-1) e^2) + x_3 (-5 e^1 + 4 e^2) + x_4 (1 e^1 + 7 e^2) \\
&= (2 x_1 + 3 x_2 + (-5) x_3 + 1 x_4) e^1 + (1 x_1 + (-1) x_2 + 4 x_3 + 7 x_4) e^2
\end{aligned}
$$

Thus we know the associated matrix $A$ of $L$ is

$$
A = \begin{pmatrix}
2 & 3 & -5 & 1 \\
1 & -1 & 4 & 7
\end{pmatrix}
$$

In [11]:
## Verify example 3

import numpy as np

A = np.matrix([[2, 3, -5, 1], [1, -1, 4, 7]])

E_1 = np.array([[1, 0, 0, 0]]).T
E_2 = np.array([[0, 1, 0, 0]]).T
E_3 = np.array([[0, 0, 1, 0]]).T
E_4 = np.array([[0, 0, 0, 1]]).T

print(A * E_1)
print(A * E_2)
print(A * E_3)
print(A * E_4)

[[2]
 [1]]
[[ 3]
 [-1]]
[[-5]
 [ 4]]
[[1]
 [7]]


### Example 4 (Rotations)

We can define a **rotation** in terms of matrices. Indeed, we call a linear map $L: R^2 \to R^2$ a rotation if its associated matrix can be written in the form

$$
R(\theta) = \begin{pmatrix}
\cos \theta & - \sin \theta \\
\sin \theta & \cos \theta
\end{pmatrix}
$$

The geometric justification for this definition comes from Figure 1.

![](figure_1.png)

We see that

$$
\begin{array}{l}
L(E_1) &= (\cos \theta) E_1 + (\sin \theta) E_2 \\
L(E_2) &= (- \sin \theta) E_1 + (\cos \theta) E_2
\end{array}
$$

When the matrix of the rotation is as above, we say that the rotation is by angle $\theta$.

For example, the matrix associated with a rotation by $\frac{\pi}{2}$ is

$$
R(\frac{\pi}{2}) = \begin{pmatrix}
0 & - 1 \\
1 & 0
\end{pmatrix}
$$

### Properties of matrix algebra propagate to algebra of associated linear maps

#### $L{A + B} = L_A + L_B$

##### Proof

By [theorem 3.1.1 in chapter 2](../2_matrices/2_3_multiplication_of_matrices.ipynb#Theorem-3.1.1), we have

$$
(A + B) X = A X + B X
$$

Hence

$$
L{A + B}(X) = L_A(X) + L_B(X)
$$

Thus

$$
L{A + B} = L_A + L_B
$$

#### $L_{cA} = c L_{A}$

##### Proof

Since

$$
(c A) X = c (A X)
$$

Hence

$$
L_{c A}(X) = c L_{A}(X)
$$

Thus

$$
L_{cA} = c L_{A}
$$

#### Linear map compositions and matrix multiplications

Let

$$
\begin{aligned}
F: K^n \to K^m && \text{and} && G: K^m \to K^s
\end{aligned}
$$

and let $A$ be the associated matrix of $F$ of size $m \times n$, and $B$ be the associated matrix of $G$ of size $s \times m$.

Then for any vector $X \in K^n$ we have

$$
(G \circ F)(X) = G(F(X)) = B (A X)
$$

And by [theorem 3.2 in chapter 2](../2_matrices/2_3_multiplication_of_matrices.ipynb#Theorem-3.2.), we have

$$
B (A X) = (B A) X
$$

Thus

$$
(G \circ F)(X) = (B A) X
$$

Hence the matrix product $B A$ is the matrix associated with the composite linear map $G \circ F$.

### Lemma 2.0: If $A B = I$, then $B A = I$, thus $B = A^{-1}$

#### Proof

https://math.stackexchange.com/a/3881

Let $\{x_1, ..., x_n\}$ be a basis of $K^n$. We first contend that $\{B x_1, ..., B x_n\}$ is also a basis of $K^n$.

Assume $\{B x_1, ..., B x_n\}$ is not a basis of $K^n$, thus we have $B x_1, ..., B x_n$ are linearly dependent.

Then there exists some $c_1, ..., c_n$ which are not all $= 0$ such that

$$
\begin{aligned}
c_1 B x_1 + ... + c_n B x_n &= \mathit{0} & \text{(*)}
\end{aligned}
$$

And multiplying equation by $A$, we have

$$
A (c_1 B x_1 + ... + c_n B x_n) = \mathit{0} \\
A c_1 B x_1 + ... +A  c_n B x_n = \mathit{0}
$$

And by [theorem 3.1 in chapter 2](2_matrices/2_3_multiplication_of_matrices.ipynb#Theorem-3.1.), we have
$$
A c_1 B x_1 + ... +A c_n B x_n = c_1 x_1 A B + ... + c_n x_n A B = c_1 x_1 I + ... + c_n x_1 I = (c_1 x_1 + ... + c_n x_n) I = \mathit{0}
$$

Thus

$$
c_1 x_1 + ... + c_n x_n = 0
$$

And since $\{x_1, ..., x_n\}$ is a basis of $K^n$, we know

$$
c_1 = 0, ..., c_n = 0
$$

which contradicts with **(\*)**.

Now we have proven $\{B x_1, ..., B x_n\}$ is also a basis of $K^n$. Thus every vector in $K^n$ can be written as a unique linear combination of $B x_1, ..., B x_n$. This means for any $Y \in K^n$, there exists some $X$ such that

$$
B X = Y
$$

Then we have

$$
B A Y = (B A) (B X)
$$

And by [theorem 2.3 in chapter 2](../2_matrices/2_3_multiplication_of_matrices.ipynb#Theorem-3.2.), matrix multiplication is associative, thus

$$
(B A) (B X) = ((B A) B) X = (B (A B)) X = (B I) X = B X = Y
$$

Thus

$$
B A Y = Y
$$

Thus

$$
B A = I
$$

Q.E.D.

### Theorem 2.2. Matrix invertiblity and linear independence of its columns

Let $A$ be an $n \times n$ matrix, and let $A^1, ... , A^n$ be its columns. Then $A$ is invertible if and only if $A_1, ..., A_n$ are linearly independent.

#### Proof

##### Proof: $A$ is invertible $\implies$ $A^1, ..., A^n$ are linearly independent

Let $X = (x_1, ..., x_n)$ be an element in $\operatorname{Ker} L_A$. Then

$$
L_A(X) = A X = x_1 A^1 + ... + x_n A^n = \mathit{0}
$$

And since $A$ is invertible, we can write

$$
X = I X = (A^{-1} A) X = A^{-1} (A X) = A^{-1} \mathit{0} = \mathit{0}
$$

Hence

$$
\operatorname{Ker} L_A = \{\mathit{0}\}
$$

Hence

$$
x_1 A^1 + ... + x_n A^n = \mathit{0}
$$

only when $x_1, ..., x_n$ all $= 0$. Thus $A^1, ..., A^n$ are linearly independent.

##### Proof: $A^1, ..., A^n$ are linearly independent  $\implies$ $A$ is invertible 

Since $A^1, ..., A^n$ are linearly independent, and since $A$ is an $n \times n$ matrix, we have $\{A^1, ..., A^n\}$ forms a basis in $K^n$.

Hence the unit column vectors $E^1, ..., E^n$ of $K^n$ can be expressed as linear combinations of $A^1, ..., A^n$. By [theorem 3.1 in chapter 3](../3_linear_mappings/3_2_linear_mappings.ipynb#Theorem-2.1:-Linear-mappings-and-basis), there exists a $n \times n$ matrix $B$ such that

$$
\begin{aligned}
B A^j = E^j && \text{for $j = 1, ..., n$}
\end{aligned}
$$

Thus

$$
B A = B \begin{pmatrix} A^1, \cdots, A^n \end{pmatrix} = \begin{pmatrix} E^1, \cdots, E^n \end{pmatrix} = I
$$

By [lemma 2.0](#Lemma-2.0:-If-$A-B-=-I$,-then-$B-A-=-I$,-thus-$B-=-A^{-1}$), we have $A B = I$. Thus $B = A^{-1}$. Thus $A$ is invertible.

Thus $A$ is invertible $\iff$ $A_1, ..., A_n$ are linearly independent.

Q.E.D.